# Generated by Django 3.2 on 2021-08-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name',), 'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
