# Generated by Django 3.2 on 2023-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkoffice',
            name='office_image',
            field=models.ImageField(default='office_pics/office_default.jpg', upload_to='office_pics'),
        ),
    ]
