# Generated by Django 3.2 on 2021-08-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoffice',
            name='office_image',
            field=models.ImageField(default='office_default.jpg', upload_to='office_pics'),
        ),
    ]
