# Generated by Django 3.2 on 2022-04-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220422_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userworkoffice',
            name='office_image',
            field=models.ImageField(default='office_default.jpg', upload_to='office_pics'),
        ),
    ]
